"""Build the empirical remaining-points table the live-middle calculator runs on.

The calculator needs P(final total lands between two numbers) given a live total,
the current score and the clock. There is no usable live-total history in the
warehouse -- `stg.oa_odds_tick` covers nine days and `raw.an_history` holds only
first-half/first-quarter markets -- so the distribution is reconstructed from the
thing that *is* deep: drive starts. Every drive start is an observation of
(clock, score so far), and the game's final total says how many points were still
to come.

The live total is the market's estimate of the final total, so
`live_total - current_score` is the market's estimate of remaining points. What
the calculator needs on top of that is the *spread* of remaining points around
that estimate, which is what this table stores: per (minutes remaining, expected
remaining) cell, the integer histogram of points actually scored from there on,
plus the cell mean so the histogram can be recentred on the user's number.

Output is written straight into `middle_calculator.html` as a JS object literal
between the MIDDLE_TABLE markers -- the page makes no network requests.

Run:  python -m models.totals.build_middle_table

The page is also published as an artifact at
https://claude.ai/artifact/4Y1CxComNST9GpPz7g3nXK — that copy is a snapshot, not a
live view of this file. Rebuilding the table here does NOT update it, and the stale
copy looks current because its provenance footer keeps reporting the same sample.
Republish to that URL after any rebuild you want people to see.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import duckdb

from cfb_paths import DB_PATH

HTML_PATH = Path(__file__).with_name("middle_calculator.html")

BEGIN = "// ---- MIDDLE_TABLE:BEGIN (generated by build_middle_table.py) ----"
END = "// ---- MIDDLE_TABLE:END ----"

# Finer near the end of the game: a middle at 2:00 left is a different animal
# than one at halftime, and that is where live middles actually show up.
MIN_REM_EDGES = [0, 2.5, 5, 7.5, 10, 15, 20, 25, 30, 37.5, 45, 52.5, 60.1]
EXP_REM_BIN = 10.0  # points; sigma varies only ~10% across this axis, so wide bins cost little
                    # and keep every realistic game state inside a populated cell
MIN_CELL_N = 100  # below this a cell is unusable; see docs/model-evaluation-standard.md
TAIL_EPS = 0.0005  # drop histogram mass below this to keep the page small

SAMPLE_SQL = """
with drive_start as (
    select
        dr.startPeriod                               as period,
        dr.startTime_minutes                         as clock_min,
        dr.startTime_seconds                         as clock_sec,
        dr.startOffenseScore + dr.startDefenseScore  as pts_so_far,
        g.home_points + g.away_points                as final_total,
        g.selected_total                             as pregame_total
    from stg.drives dr
    join core.fact_game g on g.game_id = dr.gameId
    where g.completed
      and g.home_points is not null
      and g.away_points is not null
      and g.selected_total is not null
      -- Clock fields carry junk in places (startTime_minutes up to 58 on a
      -- 15-minute quarter, 297 drives stamped period 0). Drop them.
      and (
            (dr.startPeriod between 1 and 4
             and dr.startTime_minutes between 0 and 15
             and dr.startTime_seconds between 0 and 59)
         or dr.startPeriod >= 5
      )
),
timed as (
    select
        final_total - pts_so_far as rem,
        case
            when period >= 5 then 0.0
            else (4 - period) * 15.0 + clock_min + clock_sec / 60.0
        end as min_rem,
        pregame_total as pregame_total
    from drive_start
),
kept as (
    -- A drive whose start score already exceeds the final total is a data error.
    select * from timed
    where rem between 0 and 120 and min_rem between 0 and 60
)
select
    {time_bucket_case} as tb,
    floor(pregame_total * min_rem / 60.0 / {exp_rem_bin}) as eb,
    rem,
    count(*) as c
from kept
group by 1, 2, 3
"""

SAMPLE_COUNT_SQL = SAMPLE_SQL.rsplit("select", 1)[0] + "select count(*) from kept"


def _time_bucket_case() -> str:
    """CASE mapping min_rem onto its MIN_REM_EDGES index, built from the edges."""
    arms = [
        f"when min_rem >= {MIN_REM_EDGES[i]} and min_rem < {MIN_REM_EDGES[i + 1]} then {i}"
        for i in range(len(MIN_REM_EDGES) - 1)
    ]
    return "case " + " ".join(arms) + " end"


def build_cells(rows) -> dict:
    """Assemble (time bucket, expected-remaining bucket) cells from grouped counts.

    `rows` are (tb, eb, rem, count) -- the grouping happens in SQL so only a few
    thousand rows cross the Python boundary rather than every drive start.
    """
    raw: dict[tuple[int, int], dict[int, int]] = {}
    for tb, eb, rem, c in rows:
        if tb is None:
            continue
        raw.setdefault((int(tb), int(eb)), {})[int(rem)] = int(c)

    cells = {}
    for (tb, eb), counts in raw.items():
        n = sum(counts.values())
        if n < MIN_CELL_N:
            continue
        mean = sum(r * c for r, c in counts.items()) / n
        lo, hi = min(counts), max(counts)
        probs = [counts.get(r, 0) / n for r in range(lo, hi + 1)]
        # Trim negligible tails from both ends, then renormalise.
        start = 0
        while start < len(probs) and probs[start] < TAIL_EPS:
            start += 1
        stop = len(probs)
        while stop > start and probs[stop - 1] < TAIL_EPS:
            stop -= 1
        probs = probs[start:stop]
        total = sum(probs)
        cells[f"{tb}|{eb}"] = {
            "n": n,
            "mean": round(mean, 3),
            "lo": lo + start,
            "p": [round(p / total, 5) for p in probs],
        }
    return cells


def render_js(cells: dict, sample_n: int, seasons: tuple[int, int]) -> str:
    payload = {
        "minRemEdges": MIN_REM_EDGES,
        "expRemBin": EXP_REM_BIN,
        "minCellN": MIN_CELL_N,
        "sampleN": sample_n,
        "seasons": list(seasons),
        "cells": cells,
    }
    return f"{BEGIN}\nconst MIDDLE_TABLE = {json.dumps(payload, separators=(',', ':'))};\n{END}"


def main() -> None:
    sql = SAMPLE_SQL.format(
        time_bucket_case=_time_bucket_case(), exp_rem_bin=EXP_REM_BIN
    )
    con = duckdb.connect(str(DB_PATH), read_only=True)
    try:
        rows = con.execute(sql).fetchall()
        sample_n = con.execute(
            SAMPLE_COUNT_SQL.format(
                time_bucket_case=_time_bucket_case(), exp_rem_bin=EXP_REM_BIN
            )
        ).fetchone()[0]
        seasons = con.execute(
            "select min(season), max(season) from core.fact_game "
            "where completed and selected_total is not null"
        ).fetchone()
    finally:
        con.close()

    cells = build_cells(rows)
    if not cells:
        raise SystemExit("no cells met the minimum trial count; aborting")

    block = render_js(cells, sample_n, seasons)
    html = HTML_PATH.read_text(encoding="utf-8")
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(html):
        raise SystemExit(f"MIDDLE_TABLE markers not found in {HTML_PATH}")
    HTML_PATH.write_text(pattern.sub(lambda _: block, html, count=1), encoding="utf-8")

    kept = sum(c["n"] for c in cells.values())
    print(f"✅ sample rows: {sample_n:,} (seasons {seasons[0]}-{seasons[1]})")
    print(f"✅ cells kept (n >= {MIN_CELL_N}): {len(cells)} covering {kept:,} observations")
    print(f"✅ inlined into {HTML_PATH.name} ({len(block):,} chars)")
    thin = sorted(cells.items(), key=lambda kv: kv[1]["n"])[:5]
    print("   thinnest cells: " + ", ".join(f"{k}(n={v['n']})" for k, v in thin))


if __name__ == "__main__":
    main()
